# Generated by Django 3.1 on 2020-09-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
