# Generated by Django 3.1 on 2020-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
