# Generated by Django 3.1 on 2020-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20200924_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfood',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
