# Generated by Django 3.1 on 2020-08-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20200825_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
