# Generated by Django 3.1 on 2020-09-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_auto_20200917_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='food_selected',
        ),
        migrations.AddField(
            model_name='profile',
            name='food_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calories.food'),
        ),
    ]
