# Generated by Django 3.1 on 2020-08-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_auto_20200825_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='amount',
            new_name='quantity',
        ),
    ]
