# Generated by Django 3.1 on 2020-08-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_auto_20200825_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_calorie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calorie_count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
