# Generated by Django 3.1 on 2020-09-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0006_auto_20200830_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='food_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calories.food'),
        ),
    ]
