# Generated by Django 3.1 on 2020-09-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0007_auto_20200920_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='food_selected_today',
        ),
    ]
