# Generated by Django 3.1 on 2020-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0008_remove_profile_food_selected_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='food_selected',
        ),
        migrations.AddField(
            model_name='profile',
            name='food_selected',
            field=models.ManyToManyField(blank=True, null=True, to='calories.Food'),
        ),
    ]
